name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 7,9,11 * * 1,3" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "ranbeersingh0520@gmail.com"
          git config --local user.name "dexxlabs"
          git add -A
          
          arr[0] = "UX Improvements | Bug Fixes"
          arr[1] = "New Screen Added | Performance Improvement"
          arr[2] = "Updated Dependencies"
          arr[3] = "UI Cleanup | Code Optimization"
          arr[4] = "State Management Improvements"
          arr[5] = "Navigation Flow Updated"
          arr[6] = "Refactored Components"
          arr[7] = "API Integration Updates"
          arr[8] = "Improved Load Times"
          arr[9] = "Removed Unused Code"

          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
